### ISSUE TITLE
presentation generated from generateDeck is not working out of the box 

### ISSUE THREAD

**Issue by ehmkah** [docToolchain/docToolchain#523]
**Describe the bug**
When I run "generateDeck" presentation is generated, but reveal.js directory is copied to wrong directory.

**To Reproduce**
1. create a presentation.adoc in your srcDir
2. configure in Config.groovy that it has `formats: ['revealjs']`
3. run generateDeck
4. goto srcDir/build/decks/
5. you see presentation.html andpptDirectory
6. open presentation in editor and you see that reveal.js is included `reveal.js/lib/css/zenburn.css` 
7. the reveal.js directory is under ppt/ and not on the same level as presentation.adoc

**Expected behavior**
should work without copying, and so reveal.js should be placed above ppt. Or?

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6233328/105837822-83db7a00-5fcf-11eb-8ec0-c3564cf6eaeb.png)

**Configuration**
 - OS:. Windows
 - Browser all
 - Relevant SDK Versions java 1.8 

Example:
exportContributors throws exception when ...

**Comment by ehmkah** [comment]
has been fixed with PR https://github.com/docToolchain/docToolchain/pull/524

**Comment by ghilainm** [comment]
I still have this issue today. Had to move my presentation to the reveal.js directory.

**Comment by rdmueller** [comment]
so let's reopen this and fix it.

**Comment by mh182** [comment]
We have to test this after integration of #1098.

**Comment by mh182** [comment]
I have no idea when this was fixed by with the upcoming release of docToolchain v3 this is fixed. The generated files are located in `build/decks` (see below).

```
➜ tree build/
build/
└── decks
    ├── presentation.html
    └── reveal.js
        ├── css
        │   ├── print
        │   │   ├── paper.css
        │   │   └── pdf.css
... <lot of revealjs files>
```
