### ISSUE TITLE
:jbake-order: values are sorted alphabetically

### ISSUE THREAD

**Issue by FelixGeisler** [docToolchain/docToolchain#764]
**Describe the bug**
`:jbake-order:` values are used as strings. This results in an alphabetical order (1, 10, 11, 2, 3, ...) of the chapters in the submenu.

**To Reproduce**
1. downloadTemplate
2. generateSite
3. See order of submenu

**Expected behavior**
The chapter order should be numerical.

**Screenshots**
![image](https://user-images.githubusercontent.com/36999644/151006958-04eebd3b-9f52-4ae7-b966-6115be3ab7d4.png)
(Glossary has for example `:jbake-order:` 12 and should be the last item.)

**Additional context**
Responsible for the ordering is the template file submenu.gsp (Line 26). You could just cast it to an integer.

**Comment by rdmueller** [comment]
thanx for reporting this. I think we have to fix this in the theme:

https://github.com/docToolchain/docToolchain/blob/ng/src/site/templates/submenu.gsp#L26

I guess the following line will fix it:

    <% menu?.sort{a, b ->(a.order as Integer) <=> (b.order as Integer) ?: a.title <=> b.title }.each { entry -> %>

**Comment by FelixGeisler** [comment]
Yes, this will work (except the little typo). 

Manually setting the jbake-order to a value that cannot be cast to an int would obviously lead to an error. But i cant see a reason to do this.

**Comment by rdmueller** [comment]
fixed typo :-) thanx.
Maybe we should do a safe conversion in case someone sets it to "one" "two" "three" :-)

**Comment by FelixGeisler** [comment]
You would have to replace the Integer conversions/comparisons in generateSite too. But than this will still not work as the user expects. The order will be "one", "three", "two". 

In my opinion the best solution is to only accept integer values for :jbake-order:. This should be mentioned in the docs. And in the generateSite.gradle below line 225 we could add something like this:
`if (line[0] == "order" && !line[1].isInteger()) throw new NumberFormatException("${line[1]} is not an Integer. :jbake-order: should always be an Integer.")`
